// See https://www.opendevstack.org/ods-documentation/ for usage and customization.

@Library('ods-jenkins-shared-library@4.x') _

odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-nodejs12:4.x',
  branchToEnvironmentMapping: [
    'master': 'dev',
    'release/': 'test',
  ]
) { context ->
  // nothing...
}
