// See https://www.opendevstack.org/ods-documentation/ for usage and customization.

@Library('ods-jenkins-shared-library@4.x') _

node { 
    dockerRegistry = env.DOCKER_REGISTRY
}

odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-maven:4.0.0',
  branchToEnvironmentMapping: [
    'master': 'dev',
    'release/': 'test',
  ]
) { context ->

  odsComponentFindOpenShiftImageOrElse(context) {
    stageBuild(context)
    odsComponentStageScanWithSonar(context)
    odsComponentStageBuildOpenShiftImage(context,[
      tailorParams: [
        "DOCKER_REGISTRY=${dockerRegistry}"
      ]
      ])
  }
  odsComponentStageRolloutOpenShiftDeployment(context)
}

def stageBuild(def context) {
  def javaOpts = "-Xmx512m"
  def gradleTestOpts = "-Xmx128m"
  def springBootEnv = context.environment
  if (springBootEnv.contains('-dev')) {
    springBootEnv = 'dev'
  }
  stage('Build and Unit Test') {
    withEnv(["TAGVERSION=${context.tagversion}", "NEXUS_HOST=${context.nexusHost}", "NEXUS_USERNAME=${context.nexusUsername}", "NEXUS_PASSWORD=${context.nexusPassword}", "JAVA_OPTS=${javaOpts}","GRADLE_TEST_OPTS=${gradleTestOpts}","ENVIRONMENT=${springBootEnv}"]) {
      def chmodXGradelw = sh(script: "chmod +x gradlew", returnStatus: true)
      def status = sh(script: "./gradlew clean build --stacktrace --no-daemon", returnStatus: true)
      if (status != 0) {
        error "Build failed!"
      }
    }
  }
}
